apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing-deployment
  namespace: sentry-test
  labels:
    app: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testing
  template:
    metadata:
      labels:
        app: testing
    spec:
      nodeSelector:
        env: sentry-new
      containers:
      - name: testing-container
        image: reyshazni/antrein-testing-v5
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: testing-service
  namespace: sentry-test
spec:
  selector:
    app: testing
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
  type: ClusterIP
